### ISSUE TITLE
"SingleIntergrator" can not be recognized

### ISSUE THREAD

**Issue by acoudgo** [gnotomista/multi_robot_task_allocation#1]
After running "rta_central_unit.m", Matlab promts "SingleIntergrator" can not be recognized.

**Comment by gnotomista** [comment]
The class SingleIntegrator is defined in the submodule `swarm_sim` which needs to be initialized, following the steps in the README, [here](https://github.com/gnotomista/multi_robot_task_allocation/blob/main/README.md#requirements). Then, run the `init.m` script before running the `rta_central_unit.m`.
